name: npm audit

on:
  push:
    branches:
      - [develop, master]
  pull_request:
    branches:
      - [develop, master]

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Audit
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.NIMBUS_GITHUB_TOKEN }}
          create_issues: false